find_package(Python3 COMPONENTS Interpreter)
#set(ENABLE_OPT)

set(VK_VALIDATION_NAME Vulkan-ValidationLayers)
set(VK_VALIDATION_NUM_VERSION 1.1.121)
set(VK_VALIDATION_VERSION v${VK_VALIDATION_NUM_VERSION})
set(VK_VALIDATION_TAR_NAME ${VK_VALIDATION_NAME}-${VK_VALIDATION_VERSION}.tar.gz)
set(VK_VALIDATION_DOWNLOAD_PATH ${CMAKE_BINARY_DIR}/downloads)
set(VK_VALIDATION_URL https://github.com/KhronosGroup/Vulkan-ValidationLayers/archive/${VK_VALIDATION_VERSION}.tar.gz)
set(VK_VALIDATION_TARBAL_PATH ${CMAKE_BINARY_DIR}/downloads/${VK_VALIDATION_TAR_NAME})
set(VK_VALIDATION_EXTRACT_PATH ${CMAKE_BINARY_DIR}/downloads)

if(NOT EXISTS ${VK_VALIDATION_DOWNLOAD_PATH})
    file(MAKE_DIRECTORY ${VK_VALIDATION_DOWNLOAD_PATH})
endif()

if(NOT EXISTS ${VK_VALIDATION_DOWNLOAD_PATH}/${VK_VALIDATION_TAR_NAME})
    message(STATUS "Downloading vulkan validation layers tarball")
    file(DOWNLOAD ${VK_VALIDATION_URL} ${VK_VALIDATION_DOWNLOAD_PATH}/${VK_VALIDATION_TAR_NAME})
endif()

if(NOT EXISTS ${VK_VALIDATION_EXTRACT_PATH}/${VK_VALIDATION_NAME}-${VK_VALIDATION_VERSION})
    message(STATUS "Extracting vulkan validation layers tarball")
    execute_process(COMMAND ${CMAKE_COMMAND} -E tar xf ${VK_VALIDATION_TARBAL_PATH}
        WORKING_DIRECTORY ${VK_VALIDATION_EXTRACT_PATH}
        RESULT_VARIABLE VK_VALIDATION_SUCCESS
        OUTPUT_QUIET)

    set(VK_VALIDATION_PATH ${CMAKE_BINARY_DIR}/downloads/${VK_VALIDATION_NAME}-${VK_VALIDATION_NUM_VERSION})

    set(VK_LAYER_PATH ${CMAKE_BINARY_DIR}/downloads/${VK_VALIDATION_NAME}-${VK_VALIDATION_NUM_VERSION}/layers)
endif()